name: Testes2

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
      
    - run: npm run report:merge
    
    - run: mpm run report:mocha 
    
    - name: Add GitHub Sponsors to Readme
      uses: JamesIves/github-sponsors-readme-action@v1.0.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh_pages
        FOLDER: mochawesome-report
